// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ExLink: typeof import('./src/components/ExLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TFooter: typeof import('./src/components/TFooter.vue')['default']
    THeader: typeof import('./src/components/THeader.vue')['default']
    VApp: typeof import('vuetify/components')['VApp']
    VAppBar: typeof import('vuetify/components')['VAppBar']
    VAvatar: typeof import('vuetify/components')['VAvatar']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCardAvatar: typeof import('vuetify/components')['VCardAvatar']
    VCardText: typeof import('vuetify/components')['VCardText']
    VCardTitle: typeof import('vuetify/components')['VCardTitle']
    VCarousel: typeof import('vuetify/components')['VCarousel']
    VCarouselItem: typeof import('vuetify/components')['VCarouselItem']
    VChip: typeof import('vuetify/components')['VChip']
    VCol: typeof import('vuetify/components')['VCol']
    VContainer: typeof import('vuetify/components')['VContainer']
    VDivider: typeof import('vuetify/components')['VDivider']
    VFadeTransition: typeof import('vuetify/components')['VFadeTransition']
    VFooter: typeof import('vuetify/components')['VFooter']
    VIcon: typeof import('vuetify/components')['VIcon']
    VImg: typeof import('vuetify/components')['VImg']
    VList: typeof import('vuetify/components')['VList']
    VListItem: typeof import('vuetify/components')['VListItem']
    VListItemAvatar: typeof import('vuetify/components')['VListItemAvatar']
    VListItemHeader: typeof import('vuetify/components')['VListItemHeader']
    VListItemSubtitle: typeof import('vuetify/components')['VListItemSubtitle']
    VListItemTitle: typeof import('vuetify/components')['VListItemTitle']
    VMain: typeof import('vuetify/components')['VMain']
    VRow: typeof import('vuetify/components')['VRow']
    VSpacer: typeof import('vuetify/components')['VSpacer']
    VToolbarTitle: typeof import('vuetify/components')['VToolbarTitle']
  }
}

export { }
